### ISSUE TITLE
NullReferenceException in xaml designer

### ISSUE THREAD

**Issue by fynv** [varon/GLWpfControl#26]
I got the following in xaml designer using v3.2.2 from Nuget.
![image](https://user-images.githubusercontent.com/8346412/100408498-fbf7f300-30a5-11eb-9965-09902d58e73a.png)

**Comment by marcotod1410** [comment]
From what I see in the code, there are two ways to set RenderContinuously property: by property on the XAML/element (as you're trying to do) and through the Start() method (by assigning the desired value of RenderContinuously on the respective property of the GLWpfControlSettings object).

For version 3.x, you're safe to use the latter method. Don't set the RenderContinuously property on the XAML, instead give it a value while making the Start() call.

However, we shouldn't have two ways of setting the value of this property, since it is misleading. My idea is to remove the RenderContinuously property from the settings object and leaving it on the control, as a regular property (backed by a dependency property, so to enable bindings).

Removing the property from the settings object is obviously a (not so big) breaking change, but we could make it only for 4.x version.

**Comment by varon** [comment]
XAML BAD. So much bloat just to define stuff in XML instead of normal code. It's crazy.  How can we stop this property from being set at all in XML? That's not the intended usage of it.

@marcotod1410  - we don't follow SEMVER for this project, as we want to keep parity with the OpenTK versions.

**Comment by marcotod1410** [comment]
Actually XAML is translated in regular C# code before compiling. So if you write `RenderContinuously="False"` in the XAML, you'll find a statement like `control.RenderContinuously = false;` in the generated code. Same for things like `RenderContinuously={Binding EnableContinuousRender}` that involves viewmodel bindings (even if the last one will not work atm, since there's no dependency property to RenderContinuously).

So the only way to disable setting it from the XAML is to completely remove the property from the control, or making the setter private.

Well, let's ask what is the intended usage. The question is: can RenderContinuously property be changed at runtime?
  - If yes, we should remove the property from the GLWpfControl.Start() argument, leaving the property on the control as is. Optionally, we should make it a dependency property, so to enable bindings.
  - If not, the RenderContinuously setter on the control must be made private. This way there's no way to set it, neither on the XAML nor in the code-behind of some parent controls. The GLWpfControl.Start() call sets the value of RenderContinuously internally and remains as is for the whole lifetime of the control.

I don't see any technical problems in making it mutable at runtime, but let's ask if we actually need it before implementing it.

**Comment by danielscherzer** [comment]
Currently changing `RenderContinuously` from `true` to `false` during run-time only works once. (https://github.com/varon/GLWpfControl/blob/master/src/GLWpfControl/GLWpfControl.cs) line 147.

**Comment by varon** [comment]
Closing.

**Comment by superraylin** [comment]
I installed OpenTK-3.3.3 and GLWpfControl-3.3.0 through NuGet in visual studio 2019. However, I'm still getting the same error in Designer after following the example in the "Getting Started" section in README.md. Do we have a solution for 3.X? Or do we have to completely avoid XAML?
